name: Lint Supabase DB
permissions:
  contents: read

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint-database:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: 2.62.0

      - name: Start local setup
        run: supabase db start

      - name: Lint the db
        run: supabase db lint --local
